<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Shared/LeadsAI.BuildingBlocks.Domain/LeadsAI.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../LeadsAI.Identity.Api/Domain/**/*.cs" Link="Domain/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
