using System.Text.Json; using Microsoft.EntityFrameworkCore; using QualifyAI.Application; using QualifyAI.Domain;
namespace QualifyAI.Infrastructure;
public sealed class CreateLeadTool(AppDbContext db):IAiTool { public string Name=>"CreateLead"; public async Task<AiToolResult> ExecuteAsync(AiToolContext c,string inputJson,CancellationToken ct=default){ using var d=JsonDocument.Parse(inputJson); var email=d.RootElement.TryGetProperty("email",out var e)?e.GetString()??"":""; var contact=new Contact{TenantId=c.TenantId,Email=email}; db.Contacts.Add(contact); var lead=new Lead{TenantId=c.TenantId,ContactId=contact.Id,Score=50,Temperature=LeadTemperature.Warm,IntentSummary="Created by AI tool"}; db.Leads.Add(lead); await db.SaveChangesAsync(ct); return new(true,JsonSerializer.Serialize(new{leadId=lead.Id,contactId=contact.Id})); } }
}
public sealed class CreateTicketTool(AppDbContext db):IAiTool { public string Name=>"CreateTicket"; public async Task<AiToolResult> ExecuteAsync(AiToolContext c,string inputJson,CancellationToken ct=default){ using var d=JsonDocument.Parse(inputJson); var subject=d.RootElement.TryGetProperty("subject",out var s)?s.GetString()??"AI-created ticket":"AI-created ticket"; var t=new Ticket{TenantId=c.TenantId,ConversationId=c.ConversationId,Subject=subject,Number=$"T-{DateTime.UtcNow:yyyyMMddHHmmss}"}; db.Tickets.Add(t); await db.SaveChangesAsync(ct); return new(true,JsonSerializer.Serialize(new{t.Id,t.Number})); } }
}
public sealed class SearchKnowledgeTool(IKnowledgeRetriever retriever):IAiTool { public string Name=>"SearchKnowledge"; public async Task<AiToolResult> ExecuteAsync(AiToolContext c,string inputJson,CancellationToken ct=default){ using var d=JsonDocument.Parse(inputJson); var q=d.RootElement.TryGetProperty("query",out var p)?p.GetString()??"":""; var hits=await retriever.SearchAsync(c.TenantId,q,5,ct); return new(true,JsonSerializer.Serialize(hits)); } }
}
public sealed class AiToolRegistry(IEnumerable<IAiTool> tools):IAiToolRegistry { readonly Dictionary<string,IAiTool> _tools=tools.ToDictionary(x=>x.Name,StringComparer.OrdinalIgnoreCase); public IEnumerable<string> Names=>_tools.Keys; public IAiTool? Resolve(string name)=>_tools.GetValueOrDefault(name); }
