using System.Text;

namespace QualifyAI.Api;

public static class AutonomousAcquisitionDashboardEndpoints
{
 public static IEndpointRouteBuilder MapAutonomousAcquisitionDashboard(this IEndpointRouteBuilder app)
 {
  app.MapGet("/autonomous-acquisition",()=>Results.Content(Html(),"text/html; charset=utf-8"));
  return app;
 }
 static string Html()=>"""<!doctype html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Autonomous Acquisition</title><style>body{font-family:Inter,Arial;margin:0;background:#0b1020;color:#e8eefc}.wrap{max-width:1200px;margin:auto;padding:32px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px}.card{background:#151d33;border:1px solid #26304d;border-radius:14px;padding:18px}.muted{color:#9ca9c9}button{background:#4f7cff;color:#fff;border:0;border-radius:8px;padding:10px 14px;cursor:pointer}select,input{width:100%;box-sizing:border-box;padding:10px;background:#0f1628;color:#fff;border:1px solid #34405f;border-radius:8px}.row{display:flex;gap:10px;flex-wrap:wrap}.row>*{flex:1;min-width:160px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #26304d;text-align:left}.pill{padding:4px 8px;border-radius:99px;background:#26304d}</style></head><body><div class='wrap'><h1>Autonomous Acquisition Agent</h1><p class='muted'>Create, run and monitor autonomous customer acquisition agents.</p><div class='grid'><div class='card'><div class='muted'>Agents</div><h2 id='agentsCount'>—</h2></div><div class='card'><div class='muted'>Active</div><h2 id='activeCount'>—</h2></div><div class='card'><div class='muted'>Runs</div><h2 id='runsCount'>—</h2></div><div class='card'><div class='muted'>High-score</div><h2 id='highCount'>—</h2></div></div><div class='card' style='margin-top:20px'><div class='row'><input id='tenant' placeholder='Tenant ID'><button onclick='load()'>Load dashboard</button></div></div><div class='card' style='margin-top:20px'><h2>Agents</h2><table><thead><tr><th>Name</th><th>Template</th><th>Industry</th><th>Status</th><th>Threshold</th></tr></thead><tbody id='agents'></tbody></table></div></div><script>async function load(){let t=document.getElementById('tenant').value;if(!t)return;let a=await fetch('/api/autonomous-acquisition/tenants/'+t+'/agents').then(x=>x.json());document.getElementById('agentsCount').textContent=a.length;document.getElementById('activeCount').textContent=a.filter(x=>String(x.status).toLowerCase().includes('active')||x.status===1).length;document.getElementById('agents').innerHTML=a.map(x=>`<tr><td>${x.name}</td><td>${x.templateCode}</td><td>${x.industry||''}</td><td><span class='pill'>${x.status}</span></td><td>${x.minimumScore}</td></tr>`).join('');}</script></body></html>""";
}
