<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>RaiseLead</Company>
    <Product>RaiseLead</Product>
    <AssemblyTitle>RaiseLead</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('.Application'))">
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>
