namespace QualifyAI.Domain;
public class MeetingType : TenantEntity { public string Name { get; set; }="Demo"; public int DurationMinutes { get; set; }=30; public string LocationType { get; set; }="video"; }
public class MeetingBooking : TenantEntity { public Guid MeetingTypeId { get; set; } public Guid? ContactId { get; set; } public Guid? LeadId { get; set; } public Guid? HostUserId { get; set; } public DateTime StartsAtUtc { get; set; } public DateTime EndsAtUtc { get; set; } public string Status { get; set; }="booked"; public string ExternalEventId { get; set; }=""; }
public class SalesSequence : TenantEntity { public string Name { get; set; }=""; public bool Active { get; set; } }
public class SequenceStep : TenantEntity { public Guid SequenceId { get; set; } public int StepNumber { get; set; } public int DelayMinutes { get; set; } public string Type { get; set; }="email"; public string ConfigJson { get; set; }="{}"; }
public class SequenceEnrollment : TenantEntity { public Guid SequenceId { get; set; } public Guid ContactId { get; set; } public int CurrentStep { get; set; } public string Status { get; set; }="active"; public DateTime? NextRunAtUtc { get; set; } }
public class IntegrationConnection : TenantEntity { public string Provider { get; set; }=""; public string Name { get; set; }=""; public IntegrationStatus Status { get; set; } public string SettingsJson { get; set; }="{}"; public string SecretReference { get; set; }=""; }
public class IntegrationSyncJob : TenantEntity { public Guid ConnectionId { get; set; } public string Direction { get; set; }="outbound"; public string EntityType { get; set; }="contact"; public string Status { get; set; }="pending"; public string Error { get; set; }=""; }
public class FieldMapping : TenantEntity { public Guid ConnectionId { get; set; } public string EntityType { get; set; }="contact"; public string LocalField { get; set; }=""; public string RemoteField { get; set; }=""; }
public class WebhookSubscription : TenantEntity { public string EventName { get; set; }=""; public string TargetUrl { get; set; }=""; public string Secret { get; set; }=""; public bool Active { get; set; }=true; }
public class WebhookDelivery : TenantEntity { public Guid SubscriptionId { get; set; } public string EventName { get; set; }=""; public int StatusCode { get; set; } public bool Success { get; set; } public string ResponseBody { get; set; }=""; }
