<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Persistence/QualifyAI.Persistence.SqlServer/QualifyAI.Persistence.SqlServer.csproj" />
    <ProjectReference Include="../../Core/QualifyAI.Domain.Core/QualifyAI.Domain.Core.csproj" />
    <ProjectReference Include="../../Application/QualifyAI.Application/QualifyAI.Application.csproj" />
    <ProjectReference Include="../../Application/QualifyAI.Application.Commands/QualifyAI.Application.Commands.csproj" />
    <ProjectReference Include="../../Application/QualifyAI.Application.Queries/QualifyAI.Application.Queries.csproj" />
    <ProjectReference Include="../../Application/QualifyAI.Contracts/QualifyAI.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/QualifyAI.BuildingBlocks.Messaging/QualifyAI.BuildingBlocks.Messaging.csproj" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
  </ItemGroup>
</Project>
