namespace QualifyAI.Domain;
public class Company : TenantEntity { public string Name { get; set; }=""; public string Domain { get; set; }=""; public string Industry { get; set; }=""; public int? Employees { get; set; } public string Country { get; set; }=""; public decimal? AnnualRevenue { get; set; } }
public class Contact : TenantEntity { public Guid? CompanyId { get; set; } public string FirstName { get; set; }=""; public string LastName { get; set; }=""; public string Email { get; set; }=""; public string Phone { get; set; }=""; public string LifecycleStage { get; set; }="visitor"; }
public class Lead : TenantEntity { public Guid ContactId { get; set; } public Guid? CompanyId { get; set; } public string Source { get; set; }="web"; public int Score { get; set; } public LeadTemperature Temperature { get; set; } public string Status { get; set; }="new"; public decimal? EstimatedValue { get; set; } public string IntentSummary { get; set; }=""; }
public class Opportunity : TenantEntity { public Guid? LeadId { get; set; } public Guid? CompanyId { get; set; } public Guid? ContactId { get; set; } public Guid? PipelineStageId { get; set; } public string Name { get; set; }=""; public decimal Amount { get; set; } public OpportunityStatus Status { get; set; }=OpportunityStatus.Open; public DateTime? ExpectedCloseUtc { get; set; } }
public class CrmActivity : TenantEntity { public Guid? ContactId { get; set; } public Guid? CompanyId { get; set; } public Guid? LeadId { get; set; } public string Type { get; set; }="note"; public string Subject { get; set; }=""; public string Body { get; set; }=""; }
public class CrmTask : TenantEntity { public Guid? ContactId { get; set; } public Guid? LeadId { get; set; } public Guid? OwnerUserId { get; set; } public string Title { get; set; }=""; public DateTime? DueAtUtc { get; set; } public bool Completed { get; set; } }
public class Tag : TenantEntity { public string Name { get; set; }=""; }
public class CustomFieldDefinition : TenantEntity { public string EntityType { get; set; }="contact"; public string Key { get; set; }=""; public string Label { get; set; }=""; public string DataType { get; set; }="text"; }
public class CustomFieldValue : TenantEntity { public Guid DefinitionId { get; set; } public Guid EntityId { get; set; } public string Value { get; set; }=""; }
