namespace QualifyAI.Domain;
public class Channel : TenantEntity { public string Type { get; set; }="web"; public string Name { get; set; }="Website"; public bool Enabled { get; set; }=true; public string SettingsJson { get; set; }="{}"; }
public class Conversation : TenantEntity { public Guid? ContactId { get; set; } public Guid? LeadId { get; set; } public Guid? ChannelId { get; set; } public ConversationStatus Status { get; set; }=ConversationStatus.Open; public Guid? AssignedUserId { get; set; } public bool AiEnabled { get; set; }=true; public DateTime LastMessageAtUtc { get; set; }=DateTime.UtcNow; }
public class Message : TenantEntity { public Guid ConversationId { get; set; } public string SenderType { get; set; }="visitor"; public Guid? SenderUserId { get; set; } public string Text { get; set; }=""; public string MetadataJson { get; set; }="{}"; }
public class ConversationNote : TenantEntity { public Guid ConversationId { get; set; } public Guid UserId { get; set; } public string Text { get; set; }=""; }
public class Attachment : TenantEntity { public Guid? MessageId { get; set; } public string FileName { get; set; }=""; public string ContentType { get; set; }=""; public string Url { get; set; }=""; public long SizeBytes { get; set; } }
public class Team : TenantEntity { public string Name { get; set; }=""; }
public class Ticket : TenantEntity { public Guid? ConversationId { get; set; } public Guid? ContactId { get; set; } public string Number { get; set; }=""; public string Subject { get; set; }=""; public string Description { get; set; }=""; public TicketStatus Status { get; set; }=TicketStatus.New; public TicketPriority Priority { get; set; }=TicketPriority.Normal; public Guid? AssignedUserId { get; set; } public Guid? SlaPolicyId { get; set; } public DateTime? FirstResponseDueUtc { get; set; } public DateTime? ResolutionDueUtc { get; set; } public DateTime? ResolvedAtUtc { get; set; } }
public class SlaPolicy : TenantEntity { public string Name { get; set; }="Default"; public int FirstResponseMinutes { get; set; }=60; public int ResolutionMinutes { get; set; }=480; public bool BusinessHoursOnly { get; set; }=true; }
public class TicketEvent : TenantEntity { public Guid TicketId { get; set; } public string Type { get; set; }="created"; public string DataJson { get; set; }="{}"; }
public class CsatResponse : TenantEntity { public Guid ConversationId { get; set; } public int Score { get; set; } public string Comment { get; set; }=""; }
