namespace QualifyAI.Domain;
public class KnowledgeBase : TenantEntity { public string Name { get; set; }="Default"; public string Description { get; set; }=""; }
public class KnowledgeSource : TenantEntity { public Guid KnowledgeBaseId { get; set; } public string Type { get; set; }="manual"; public string Name { get; set; }=""; public string Location { get; set; }=""; public string Status { get; set; }="ready"; public DateTime? LastSyncedAtUtc { get; set; } }
public class KnowledgeDocument : TenantEntity { public Guid KnowledgeBaseId { get; set; } public Guid? SourceId { get; set; } public string Title { get; set; }=""; public string Body { get; set; }=""; public int Version { get; set; }=1; public bool Published { get; set; }=true; }
public class KnowledgeChunk : TenantEntity { public Guid DocumentId { get; set; } public int ChunkIndex { get; set; } public string Text { get; set; }=""; public string VectorJson { get; set; }="[]"; }
public class KnowledgeGap : TenantEntity { public string Topic { get; set; }=""; public int Occurrences { get; set; } public string ExampleQuestion { get; set; }=""; public string Status { get; set; }="open"; public decimal ImpactScore { get; set; } }
public class AiAgent : TenantEntity { public string Name { get; set; }="AI Agent"; public string Role { get; set; }="Support and Sales"; public string Instructions { get; set; }=""; public string Tone { get; set; }="professional"; public string Model { get; set; }="local"; public string LanguagesCsv { get; set; }="en"; public bool Active { get; set; }=true; public Guid? KnowledgeBaseId { get; set; } }
public class AiAgentVersion : TenantEntity { public Guid AgentId { get; set; } public int Version { get; set; } public string ConfigurationJson { get; set; }="{}"; public bool Published { get; set; } }
public class AiToolDefinition : TenantEntity { public string Name { get; set; }=""; public string Description { get; set; }=""; public string InputSchemaJson { get; set; }="{}"; public string RequiredPermission { get; set; }=""; public bool Enabled { get; set; }=true; }
public class AiToolExecution : TenantEntity { public Guid? AgentId { get; set; } public Guid? ConversationId { get; set; } public string ToolName { get; set; }=""; public string InputJson { get; set; }="{}"; public string OutputJson { get; set; }="{}"; public bool Success { get; set; } public long DurationMs { get; set; } }
public class PromptVersion : TenantEntity { public Guid AgentId { get; set; } public int Version { get; set; } public string Prompt { get; set; }=""; public bool Active { get; set; } }
