<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../LeadsAI.Identity.Persistence.SqlServer/LeadsAI.Identity.Persistence.SqlServer.csproj" />
    <ProjectReference Include="../LeadsAI.Identity.Domain/LeadsAI.Identity.Domain.csproj" />
    <ProjectReference Include="../LeadsAI.Identity.Application/LeadsAI.Identity.Application.csproj" />
    <ProjectReference Include="../../Shared/LeadsAI.BuildingBlocks.Messaging/LeadsAI.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="../../Shared/LeadsAI.BuildingBlocks.Security/LeadsAI.BuildingBlocks.Security.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
  </ItemGroup>
</Project>
