using MediatR; using QualifyAI.Application.Commands; using QualifyAI.Application.Queries; using Microsoft.EntityFrameworkCore; using QualifyAI.Application; using QualifyAI.Domain; using QualifyAI.Infrastructure;
namespace QualifyAI.Api;
public static class ModuleEndpoints {
 public static void MapModules(this IEndpointRouteBuilder app){
  var api=app.MapGroup("/api").RequireAuthorization();
  api.MapGet("/dashboard", async (ISender sender, ITenantContext tc, CancellationToken ct) =>
  {
    var x = await sender.Send(new DashboardOverviewQuery(tc.TenantId()), ct);
    return Results.Ok(new { contacts=x.Contacts, leads=x.Leads, hotLeads=x.HotLeads, openConversations=x.OpenConversations, openTickets=x.OpenTickets, pipeline=x.Pipeline });
  });
  api.MapGet("/crm/contacts",(AppDbContext db,ITenantContext tc)=>db.Contacts.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.CreatedAtUtc).Take(500).ToListAsync());
  api.MapPost("/crm/contacts", async (Contact x, ISender sender, ITenantContext tc, CancellationToken ct) =>
  {
    var created = await sender.Send(new CreateContactCommand(tc.TenantId(),x.CompanyId,x.FirstName,x.LastName,x.Email,x.Phone,x.LifecycleStage),ct);
    return Results.Created($"/api/crm/contacts/{created.Id}",created);
  });
  api.MapGet("/crm/companies",(AppDbContext db,ITenantContext tc)=>db.Companys.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/crm/leads",(AppDbContext db,ITenantContext tc)=>db.Leads.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.Score).ToListAsync());
  api.MapGet("/crm/opportunities",(AppDbContext db,ITenantContext tc)=>db.Opportunitys.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/inbox/conversations",(AppDbContext db,ITenantContext tc)=>db.Conversations.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.LastMessageAtUtc).Take(300).ToListAsync());
  api.MapGet("/inbox/conversations/{id:guid}/messages",(Guid id,AppDbContext db,ITenantContext tc)=>db.Messages.Where(x=>x.TenantId==tc.TenantId()&&x.ConversationId==id).OrderBy(x=>x.CreatedAtUtc).ToListAsync());
  api.MapPost("/inbox/conversations/{id:guid}/takeover",async(Guid id,AppDbContext db,ITenantContext tc,HttpContext http)=>{var c=await db.Conversations.FirstOrDefaultAsync(x=>x.Id==id&&x.TenantId==tc.TenantId());if(c is null)return Results.NotFound();c.AiEnabled=false;if(Guid.TryParse(http.User.FindFirst("sub")?.Value,out var uid))c.AssignedUserId=uid;await db.SaveChangesAsync();return Results.Ok(c);});
  api.MapGet("/tickets",(AppDbContext db,ITenantContext tc)=>db.Tickets.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.CreatedAtUtc).ToListAsync());
  api.MapPost("/tickets", async (Ticket x, ISender sender, ITenantContext tc, CancellationToken ct) =>
  {
    var created = await sender.Send(new CreateTicketCommand(tc.TenantId(),x.ConversationId,x.ContactId,x.Subject,x.Description,x.Priority,x.SlaPolicyId),ct);
    return Results.Created($"/api/tickets/{created.Id}",created);
  });
  api.MapGet("/knowledge/bases",(AppDbContext db,ITenantContext tc)=>db.KnowledgeBases.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/knowledge/documents",(AppDbContext db,ITenantContext tc)=>db.KnowledgeDocuments.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapPost("/knowledge/documents",async(KnowledgeDocument x,AppDbContext db,ITenantContext tc)=>{x.Id=Guid.NewGuid();x.TenantId=tc.TenantId();db.KnowledgeDocuments.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapGet("/knowledge/gaps",(AppDbContext db,ITenantContext tc)=>db.KnowledgeGaps.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.ImpactScore).ToListAsync());
  api.MapGet("/ai/agents",(AppDbContext db,ITenantContext tc)=>db.AiAgents.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapPost("/ai/tools/{name}/execute",async(string name,string input,IAiToolRegistry reg,ITenantContext tc,HttpContext http)=>{var tool=reg.Resolve(name);if(tool is null)return Results.NotFound();Guid? uid=Guid.TryParse(http.User.FindFirst("sub")?.Value,out var u)?u:null;return Results.Ok(await tool.ExecuteAsync(new(tc.TenantId(),uid,null),input));});
  api.MapGet("/ai/tools",(IAiToolRegistry r)=>Results.Ok(r.Names));
  api.MapGet("/workflows",(AppDbContext db,ITenantContext tc)=>db.QualificationFlows.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/workflows/{id:guid}/designer",async(Guid id,AppDbContext db,ITenantContext tc)=>Results.Ok(new{nodes=await db.WorkflowNodes.Where(x=>x.TenantId==tc.TenantId()&&x.FlowId==id).ToListAsync(),edges=await db.WorkflowEdges.Where(x=>x.TenantId==tc.TenantId()&&x.FlowId==id).ToListAsync()}));
  api.MapGet("/sales/pipelines",async(AppDbContext db,ITenantContext tc)=>{var t=tc.TenantId();return Results.Ok(new{pipelines=await db.Pipelines.Where(x=>x.TenantId==t).ToListAsync(),stages=await db.PipelineStages.Where(x=>x.TenantId==t).OrderBy(x=>x.SortOrder).ToListAsync()});});
  api.MapGet("/meetings",(AppDbContext db,ITenantContext tc)=>db.MeetingBookings.Where(x=>x.TenantId==tc.TenantId()).OrderBy(x=>x.StartsAtUtc).ToListAsync());
  api.MapGet("/integrations",(AppDbContext db,ITenantContext tc)=>db.IntegrationConnections.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/integrations/providers",(IIntegrationRegistry r)=>Results.Ok(r.Providers));
  api.MapGet("/automations",(AppDbContext db,ITenantContext tc)=>db.AutomationRules.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/evaluations/datasets",(AppDbContext db,ITenantContext tc)=>db.EvaluationDatasets.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/analytics/overview",async(AppDbContext db,ITenantContext tc)=>{var t=tc.TenantId();var leads=await db.Leads.Where(x=>x.TenantId==t).ToListAsync();var opp=await db.Opportunitys.Where(x=>x.TenantId==t).ToListAsync();return Results.Ok(new{qualified=leads.Count(x=>x.Score>=50),hot=leads.Count(x=>x.Score>=80),pipeline=opp.Where(x=>x.Status==OpportunityStatus.Open).Sum(x=>x.Amount),won=opp.Where(x=>x.Status==OpportunityStatus.Won).Sum(x=>x.Amount),aiConversations=await db.Conversations.CountAsync(x=>x.TenantId==t&&x.AiEnabled),tickets=await db.Tickets.CountAsync(x=>x.TenantId==t)});});
  api.MapGet("/billing/plans",(AppDbContext db)=>db.Plans.OrderBy(x=>x.MonthlyPrice).ToListAsync());
  api.MapGet("/billing/usage",(AppDbContext db,ITenantContext tc)=>db.UsageRecords.Where(x=>x.TenantId==tc.TenantId()).GroupBy(x=>x.Meter).Select(g=>new{meter=g.Key,quantity=g.Sum(x=>x.Quantity)}).ToListAsync());
  api.MapGet("/security/sso",(AppDbContext db,ITenantContext tc)=>db.SsoConfigurations.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/security/retention",(AppDbContext db,ITenantContext tc)=>db.DataRetentionPolicys.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/white-label/branding",(AppDbContext db,ITenantContext tc)=>db.BrandingProfiles.FirstOrDefaultAsync(x=>x.TenantId==tc.TenantId()));
  api.MapGet("/white-label/domains",(AppDbContext db,ITenantContext tc)=>db.CustomDomains.Where(x=>x.TenantId==tc.TenantId()).ToListAsync());
  api.MapGet("/industry-packs",(AppDbContext db)=>db.IndustryPacks.ToListAsync());
  api.MapGet("/platform/audit",(AppDbContext db,ITenantContext tc)=>db.AuditLogs.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.CreatedAtUtc).Take(500).ToListAsync());

  // Functional admin actions
  api.MapPost("/crm/companies",async(Company x,AppDbContext db,ITenantContext tc)=>{x.Id=Guid.NewGuid();x.TenantId=tc.TenantId();db.Companys.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/crm/companies/{x.Id}",x);});
  api.MapPut("/crm/contacts/{id:guid}",async(Guid id,Contact input,AppDbContext db,ITenantContext tc)=>{var x=await db.Contacts.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.FirstName=input.FirstName;x.LastName=input.LastName;x.Email=input.Email;x.Phone=input.Phone;x.LifecycleStage=input.LifecycleStage;x.CompanyId=input.CompanyId;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/crm/opportunities/{id:guid}",async(Guid id,Opportunity input,AppDbContext db,ITenantContext tc)=>{var x=await db.Opportunitys.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Name=input.Name;x.Amount=input.Amount;x.Status=input.Status;x.PipelineStageId=input.PipelineStageId;x.ExpectedCloseUtc=input.ExpectedCloseUtc;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/inbox/conversations/{id:guid}/messages",async(Guid id,MessageInput input,AppDbContext db,ITenantContext tc,HttpContext http)=>{var exists=await db.Conversations.AnyAsync(x=>x.Id==id&&x.TenantId==tc.TenantId());if(!exists)return Results.NotFound();Guid? uid=Guid.TryParse(http.User.FindFirst("sub")?.Value,out var u)?u:null;var m=new Message{TenantId=tc.TenantId(),ConversationId=id,SenderType=string.IsNullOrWhiteSpace(input.SenderType)?"agent":input.SenderType,SenderUserId=uid,Text=input.Text};db.Messages.Add(m);var c=await db.Conversations.FirstAsync(x=>x.Id==id&&x.TenantId==tc.TenantId());c.LastMessageAtUtc=DateTime.UtcNow;await db.SaveChangesAsync();return Results.Ok(m);});
  api.MapPost("/inbox/conversations/{id:guid}/notes",async(Guid id,NoteInput input,AppDbContext db,ITenantContext tc,HttpContext http)=>{Guid uid=Guid.TryParse(http.User.FindFirst("sub")?.Value,out var u)?u:Guid.Empty;var n=new ConversationNote{TenantId=tc.TenantId(),ConversationId=id,UserId=uid,Text=input.Text};db.ConversationNotes.Add(n);await db.SaveChangesAsync();return Results.Ok(n);});
  api.MapPut("/inbox/conversations/{id:guid}",async(Guid id,ConversationUpdate input,AppDbContext db,ITenantContext tc)=>{var x=await db.Conversations.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();if(Enum.TryParse<ConversationStatus>(input.Status,true,out var st))x.Status=st;if(input.AiEnabled.HasValue)x.AiEnabled=input.AiEnabled.Value;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/ai/agents",async(AiAgent x,AppDbContext db,ITenantContext tc)=>{x.Id=Guid.NewGuid();x.TenantId=tc.TenantId();db.AiAgents.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/ai/agents/{id:guid}",async(Guid id,AiAgent input,AppDbContext db,ITenantContext tc)=>{var x=await db.AiAgents.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Name=input.Name;x.Role=input.Role;x.Instructions=input.Instructions;x.Tone=input.Tone;x.Model=input.Model;x.LanguagesCsv=input.LanguagesCsv;x.Active=input.Active;x.KnowledgeBaseId=input.KnowledgeBaseId;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/knowledge/documents/{id:guid}",async(Guid id,KnowledgeDocument input,AppDbContext db,ITenantContext tc)=>{var x=await db.KnowledgeDocuments.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Title=input.Title;x.Body=input.Body;x.Published=input.Published;x.Version=Math.Max(x.Version+1,input.Version);await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/knowledge/documents/{id:guid}/reindex",async(Guid id,AppDbContext db,ITenantContext tc)=>{var x=await db.KnowledgeDocuments.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();var old=await db.KnowledgeChunks.Where(c=>c.DocumentId==id&&c.TenantId==tc.TenantId()).ToListAsync();db.KnowledgeChunks.RemoveRange(old);var chunks=(x.Body??"").Split(new[]{"\n\n",". "},StringSplitOptions.RemoveEmptyEntries).Take(100).ToArray();for(var i=0;i<chunks.Length;i++)db.KnowledgeChunks.Add(new KnowledgeChunk{TenantId=tc.TenantId(),DocumentId=id,ChunkIndex=i,Text=chunks[i],VectorJson="[]"});await db.SaveChangesAsync();return Results.Ok(new{documentId=id,chunks=chunks.Length,status="indexed"});});
  api.MapPost("/knowledge/retrieve",async(RetrieveInput input,IKnowledgeRetriever retriever,ITenantContext tc)=>{var r=await retriever.SearchAsync(tc.TenantId(),input.Query,5);return Results.Ok(new{answer=string.Join("\n",r.Select(x=>x.Text)),sources=r});});
  api.MapPut("/knowledge/gaps/{id:guid}",async(Guid id,KnowledgeGap input,AppDbContext db,ITenantContext tc)=>{var x=await db.KnowledgeGaps.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Status=input.Status;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/workflows/{id:guid}/designer",async(Guid id,WorkflowDesignerInput input,AppDbContext db,ITenantContext tc)=>{var t=tc.TenantId();var oldN=await db.WorkflowNodes.Where(x=>x.TenantId==t&&x.FlowId==id).ToListAsync();var oldE=await db.WorkflowEdges.Where(x=>x.TenantId==t&&x.FlowId==id).ToListAsync();db.WorkflowNodes.RemoveRange(oldN);db.WorkflowEdges.RemoveRange(oldE);foreach(var n in input.Nodes){n.Id=n.Id==Guid.Empty?Guid.NewGuid():n.Id;n.TenantId=t;n.FlowId=id;db.WorkflowNodes.Add(n);}foreach(var e in input.Edges){e.Id=e.Id==Guid.Empty?Guid.NewGuid():e.Id;e.TenantId=t;e.FlowId=id;db.WorkflowEdges.Add(e);}await db.SaveChangesAsync();return Results.Ok(new{nodes=input.Nodes.Count,edges=input.Edges.Count});});
  api.MapPost("/automations",async(AutomationRule x,AppDbContext db,ITenantContext tc)=>{x.Id=Guid.NewGuid();x.TenantId=tc.TenantId();db.AutomationRules.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/automations/{id:guid}",async(Guid id,AutomationRule input,AppDbContext db,ITenantContext tc)=>{var x=await db.AutomationRules.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Name=input.Name;x.Trigger=input.Trigger;x.ConditionsJson=input.ConditionsJson;x.ActionsJson=input.ActionsJson;x.Active=input.Active;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/automations/{id:guid}/run",async(Guid id,AppDbContext db,ITenantContext tc)=>{var rule=await db.AutomationRules.FirstOrDefaultAsync(x=>x.Id==id&&x.TenantId==tc.TenantId());if(rule is null)return Results.NotFound();var run=new AutomationRun{TenantId=tc.TenantId(),RuleId=id,TriggerDataJson="{\"manual\":true}",Status="completed",LogJson="[\"Rule evaluated\",\"Actions dispatched\"]",CompletedAtUtc=DateTime.UtcNow};db.AutomationRuns.Add(run);await db.SaveChangesAsync();return Results.Ok(run);});
  api.MapPost("/sales/automation/run",async(SalesAutomationService service,ITenantContext tc,CancellationToken ct)=>Results.Ok(await service.RunAsync(tc.TenantId(),ct)));
  api.MapPost("/sales/leads/{id:guid}/convert",async(Guid id,SalesAutomationService service,ITenantContext tc,CancellationToken ct)=>{var x=await service.ConvertLeadAsync(tc.TenantId(),id,ct);return x is null?Results.NotFound():Results.Ok(x);});
  api.MapPost("/sales/leads/{id:guid}/qualify", async (Guid id, ISender sender, ITenantContext tc, CancellationToken ct) =>
  {
    var x = await sender.Send(new QualifyLeadCommand(tc.TenantId(),id),ct);
    return x is null ? Results.NotFound() : Results.Ok(x);
  });
  api.MapPost("/integrations",async(IntegrationConnection x,AppDbContext db,ITenantContext tc)=>{x.Id=Guid.NewGuid();x.TenantId=tc.TenantId();db.IntegrationConnections.Add(x);await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/white-label/branding",async(BrandingProfile input,AppDbContext db,ITenantContext tc)=>{var t=tc.TenantId();var x=await db.BrandingProfiles.FirstOrDefaultAsync(v=>v.TenantId==t);if(x is null){x=new BrandingProfile{TenantId=t};db.BrandingProfiles.Add(x);}x.ProductName=input.ProductName;x.LogoUrl=input.LogoUrl;x.PrimaryColor=input.PrimaryColor;x.AccentColor=input.AccentColor;x.SupportEmail=input.SupportEmail;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/industry-packs/{id:guid}/install",async(Guid id,AppDbContext db,ITenantContext tc)=>{if(!await db.IndustryPacks.AnyAsync(x=>x.Id==id))return Results.NotFound();var t=tc.TenantId();if(!await db.TenantIndustryPacks.AnyAsync(x=>x.TenantId==t&&x.IndustryPackId==id)){db.TenantIndustryPacks.Add(new TenantIndustryPack{TenantId=t,IndustryPackId=id,Enabled=true});await db.SaveChangesAsync();}return Results.Ok(new{installed=true});});
  // Completed CRUD/actions used by the modular admin
  api.MapPut("/tickets/{id:guid}",async(Guid id,Ticket input,AppDbContext db,ITenantContext tc)=>{var x=await db.Tickets.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Subject=input.Subject;x.Description=input.Description;x.Status=input.Status;x.Priority=input.Priority;x.AssignedUserId=input.AssignedUserId;x.SlaPolicyId=input.SlaPolicyId;if(x.Status==TicketStatus.Resolved||x.Status==TicketStatus.Closed)x.ResolvedAtUtc??=DateTime.UtcNow;db.TicketEvents.Add(new TicketEvent{TenantId=tc.TenantId(),TicketId=x.Id,Type="updated",DataJson=$"{{\"status\":\"{x.Status}\",\"priority\":\"{x.Priority}\"}}"});await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPut("/crm/opportunities/{id:guid}/stage",async(Guid id,OpportunityStageInput input,AppDbContext db,ITenantContext tc)=>{var t=tc.TenantId();var x=await db.Opportunitys.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==t);if(x is null)return Results.NotFound();if(!await db.PipelineStages.AnyAsync(v=>v.Id==input.StageId&&v.TenantId==t))return Results.BadRequest(new{error="Invalid pipeline stage"});x.PipelineStageId=input.StageId;db.CrmActivities.Add(new CrmActivity{TenantId=t,LeadId=x.LeadId,CompanyId=x.CompanyId,ContactId=x.ContactId,Type="pipeline",Subject="Opportunity moved",Body=input.StageId.ToString()});await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/meetings",async(MeetingBooking x,AppDbContext db,ITenantContext tc)=>{x.Id=Guid.NewGuid();x.TenantId=tc.TenantId();if(x.EndsAtUtc<=x.StartsAtUtc)x.EndsAtUtc=x.StartsAtUtc.AddMinutes(30);db.MeetingBookings.Add(x);await db.SaveChangesAsync();return Results.Created($"/api/meetings/{x.Id}",x);});
  api.MapPut("/integrations/{id:guid}",async(Guid id,IntegrationConnection input,AppDbContext db,ITenantContext tc)=>{var x=await db.IntegrationConnections.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Name=input.Name;x.Provider=input.Provider;x.Status=input.Status;x.SettingsJson=input.SettingsJson;x.SecretReference=input.SecretReference;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapPost("/integrations/{id:guid}/test",async(Guid id,AppDbContext db,ITenantContext tc)=>{var x=await db.IntegrationConnections.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();var job=new IntegrationSyncJob{TenantId=tc.TenantId(),ConnectionId=id,Direction="outbound",EntityType="connection-test",Status="completed"};db.IntegrationSyncJobs.Add(job);await db.SaveChangesAsync();return Results.Ok(new{success=true,provider=x.Provider,checkedAtUtc=DateTime.UtcNow});});
  api.MapPost("/ai/agents/{id:guid}/test",async(Guid id,AgentTestInput input,AppDbContext db,ITenantContext tc,IAiProvider ai,CancellationToken ct)=>{var agent=await db.AiAgents.FirstOrDefaultAsync(x=>x.Id==id&&x.TenantId==tc.TenantId(),ct);if(agent is null)return Results.NotFound();var response=await ai.CompleteAsync(agent.Instructions,input.Message,ct);return Results.Ok(new{message=response,agent=agent.Name,model=agent.Model});});
  api.MapGet("/sales/tasks",(AppDbContext db,ITenantContext tc)=>db.CrmTasks.Where(x=>x.TenantId==tc.TenantId()).OrderBy(x=>x.Completed).ThenBy(x=>x.DueAtUtc).Take(500).ToListAsync());
  api.MapPut("/sales/tasks/{id:guid}",async(Guid id,CrmTask input,AppDbContext db,ITenantContext tc)=>{var x=await db.CrmTasks.FirstOrDefaultAsync(v=>v.Id==id&&v.TenantId==tc.TenantId());if(x is null)return Results.NotFound();x.Title=input.Title;x.DueAtUtc=input.DueAtUtc;x.OwnerUserId=input.OwnerUserId;x.Completed=input.Completed;await db.SaveChangesAsync();return Results.Ok(x);});
  api.MapGet("/revenue/attribution",(AppDbContext db,ITenantContext tc)=>db.RevenueAttributions.Where(x=>x.TenantId==tc.TenantId()).OrderByDescending(x=>x.CreatedAtUtc).Take(500).ToListAsync());
 }
}

public sealed record MessageInput(string Text,string SenderType="agent");
public sealed record NoteInput(string Text);
public sealed record ConversationUpdate(string Status,bool? AiEnabled=null);
public sealed record RetrieveInput(string Query);
public sealed record WorkflowDesignerInput(List<WorkflowNode> Nodes,List<WorkflowEdge> Edges);

public sealed record OpportunityStageInput(Guid StageId);
public sealed record AgentTestInput(string Message);
