using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using QualifyAI.Api;
using QualifyAI.Application;
using QualifyAI.BuildingBlocks.Security;
using QualifyAI.Infrastructure;

var builder=WebApplication.CreateBuilder(args);
builder.AddServiceDefaults();
builder.Services.AddMediatR(cfg => cfg.RegisterServicesFromAssemblyContaining<DashboardOverviewQueryHandler>());
builder.Services.AddDbContext<AppDbContext>(o=>o.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"),sql=>sql.EnableRetryOnFailure()));
builder.Services.AddScoped<ITenantContext,TenantContext>();
builder.Services.AddScoped<LeadQualificationService>();
builder.Services.AddScoped<WorkflowEngine>();
builder.Services.AddScoped<SlaService>();
builder.Services.AddScoped<KnowledgeGapService>();
builder.Services.AddScoped<BillingService>();
builder.Services.AddScoped<IKnowledgeRetriever,SqlKnowledgeRetriever>();
builder.Services.AddScoped<IAiProvider,LocalAiProvider>();
builder.Services.AddScoped<IAiTool,CreateLeadTool>();
builder.Services.AddScoped<IAiTool,CreateTicketTool>();
builder.Services.AddScoped<IAiTool,SearchKnowledgeTool>();
builder.Services.AddScoped<IAiToolRegistry,AiToolRegistry>();
builder.Services.AddHttpClient<IIntegrationProvider,GenericWebhookIntegration>();
builder.Services.AddScoped<IIntegrationRegistry,IntegrationRegistry>();
builder.Services.AddScoped<SalesAutomationService>();
builder.Services.Configure<RevenueAutomationOptions>(builder.Configuration.GetSection("RevenueAutomation"));
builder.Services.AddHostedService<RevenueAutomationWorker>();
builder.Services.AddScoped<DemoSeeder>();
builder.Services.AddSignalR();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c=>{c.SwaggerDoc("v1",new OpenApiInfo{Title="QualifyAI Business API",Version="v1"});c.AddSecurityDefinition("Bearer",new OpenApiSecurityScheme{Type=SecuritySchemeType.Http,Scheme="bearer",BearerFormat="JWT"});});
builder.Services.AddQualifyAiResourceServer(builder.Configuration);
builder.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin()));

var app=builder.Build();
app.MapDefaultEndpoints();
app.UseCors();
app.UseSwagger();
app.UseSwaggerUI();
app.UseAuthentication();
app.UseMiddleware<TenantMiddleware>();
app.UseAuthorization();
app.MapHub<ConversationHub>("/hubs/conversations");
app.MapPublicChat();
app.MapModules();
app.MapExtendedAdmin();
app.MapGet("/internal/tenants/by-slug/{slug}",async(string slug,AppDbContext db)=>{var t=await db.Tenants.AsNoTracking().FirstOrDefaultAsync(x=>x.Slug==slug&&x.IsActive);return t is null?Results.NotFound():Results.Ok(new{t.Id,t.Slug,t.Name,t.IsActive});}).AllowAnonymous();
using(var scope=app.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<AppDbContext>();if(app.Environment.IsDevelopment())await db.Database.EnsureCreatedAsync();else await db.Database.MigrateAsync();await scope.ServiceProvider.GetRequiredService<DemoSeeder>().SeedAsync();}
app.Run();
