<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../QualifyAI.AIOrchestration.Domain/QualifyAI.AIOrchestration.Domain.csproj" />
<ProjectReference Include="../QualifyAI.AIOrchestration.Application/QualifyAI.AIOrchestration.Application.csproj" />
<ProjectReference Include="../../../BuildingBlocks/QualifyAI.BuildingBlocks.Messaging/QualifyAI.BuildingBlocks.Messaging.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" /><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" /><PackageReference Include="MassTransit" /><PackageReference Include="MassTransit.RabbitMQ" />
  </ItemGroup>
</Project>