using Microsoft.EntityFrameworkCore;
using QualifyAI.Domain;
using QualifyAI.Domain.Core.Catalog;
using QualifyAI.Domain.Core.Portal;
using QualifyAI.Domain.Core.Promotions;
using QualifyAI.Persistence.SqlServer.Configurations;
using QualifyAI.Persistence.SqlServer.Projections;

namespace QualifyAI.Persistence.SqlServer;

public sealed class AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
{
    public DbSet<Tenant> Tenants => Set<Tenant>(); public DbSet<TenantEntitlementProjection> TenantEntitlements => Set<TenantEntitlementProjection>(); public DbSet<TenantModuleProvisioning> TenantModuleProvisionings => Set<TenantModuleProvisioning>(); public DbSet<TenantLifecycleEventRecord> TenantLifecycleEvents => Set<TenantLifecycleEventRecord>(); public DbSet<BillingEventRecord> BillingEvents => Set<BillingEventRecord>(); public DbSet<TenantBillingSubscriptionRecord> TenantBillingSubscriptions => Set<TenantBillingSubscriptionRecord>(); public DbSet<TenantBillingInvoiceRecord> TenantBillingInvoices => Set<TenantBillingInvoiceRecord>(); public DbSet<TenantBillingLifecycleRecord> TenantBillingLifecycles => Set<TenantBillingLifecycleRecord>(); public DbSet<AutonomousAcquisitionAgent> AutonomousAcquisitionAgents => Set<AutonomousAcquisitionAgent>(); public DbSet<AutonomousAcquisitionAgentRun> AutonomousAcquisitionAgentRuns => Set<AutonomousAcquisitionAgentRun>(); public DbSet<AutonomousAcquisitionAgentMemory> AutonomousAcquisitionAgentMemories => Set<AutonomousAcquisitionAgentMemory>();
    public DbSet<AppUser> AppUsers => Set<AppUser>(); public DbSet<Role> Roles => Set<Role>(); public DbSet<Permission> Permissions => Set<Permission>(); public DbSet<UserRole> UserRoles => Set<UserRole>(); public DbSet<RolePermission> RolePermissions => Set<RolePermission>(); public DbSet<AuditLog> AuditLogs => Set<AuditLog>(); public DbSet<ApiKey> ApiKeys => Set<ApiKey>(); public DbSet<Notification> Notifications => Set<Notification>(); public DbSet<TenantSetting> TenantSettings => Set<TenantSetting>();
    public DbSet<Company> Companys => Set<Company>(); public DbSet<Contact> Contacts => Set<Contact>(); public DbSet<Lead> Leads => Set<Lead>(); public DbSet<Opportunity> Opportunitys => Set<Opportunity>(); public DbSet<CrmActivity> CrmActivitys => Set<CrmActivity>(); public DbSet<CrmTask> CrmTasks => Set<CrmTask>(); public DbSet<Tag> Tags => Set<Tag>(); public DbSet<CustomFieldDefinition> CustomFieldDefinitions => Set<CustomFieldDefinition>(); public DbSet<CustomFieldValue> CustomFieldValues => Set<CustomFieldValue>(); public DbSet<Pipeline> Pipelines => Set<Pipeline>(); public DbSet<PipelineStage> PipelineStages => Set<PipelineStage>(); public DbSet<IcpProfile> IcpProfiles => Set<IcpProfile>(); public DbSet<LeadScoreExplanation> LeadScoreExplanations => Set<LeadScoreExplanation>(); public DbSet<MeetingType> MeetingTypes => Set<MeetingType>(); public DbSet<MeetingBooking> MeetingBookings => Set<MeetingBooking>(); public DbSet<SalesSequence> SalesSequences => Set<SalesSequence>(); public DbSet<SequenceStep> SequenceSteps => Set<SequenceStep>(); public DbSet<SequenceEnrollment> SequenceEnrollments => Set<SequenceEnrollment>(); public DbSet<Prospect> Prospects => Set<Prospect>(); public DbSet<ProspectSignal> ProspectSignals => Set<ProspectSignal>(); public DbSet<TargetList> TargetLists => Set<TargetList>(); public DbSet<TargetListMember> TargetListMembers => Set<TargetListMember>(); public DbSet<Campaign> Campaigns => Set<Campaign>(); public DbSet<CampaignStep> CampaignSteps => Set<CampaignStep>(); public DbSet<CampaignRecipient> CampaignRecipients => Set<CampaignRecipient>(); public DbSet<OutreachMessage> OutreachMessages => Set<OutreachMessage>(); public DbSet<ProspectReply> ProspectReplies => Set<ProspectReply>();
    public DbSet<Channel> Channels => Set<Channel>(); public DbSet<Conversation> Conversations => Set<Conversation>(); public DbSet<Message> Messages => Set<Message>(); public DbSet<ConversationNote> ConversationNotes => Set<ConversationNote>(); public DbSet<Attachment> Attachments => Set<Attachment>(); public DbSet<Team> Teams => Set<Team>(); public DbSet<Ticket> Tickets => Set<Ticket>(); public DbSet<SlaPolicy> SlaPolicys => Set<SlaPolicy>(); public DbSet<TicketEvent> TicketEvents => Set<TicketEvent>(); public DbSet<CsatResponse> CsatResponses => Set<CsatResponse>();
    public DbSet<KnowledgeBase> KnowledgeBases => Set<KnowledgeBase>(); public DbSet<KnowledgeSource> KnowledgeSources => Set<KnowledgeSource>(); public DbSet<KnowledgeDocument> KnowledgeDocuments => Set<KnowledgeDocument>(); public DbSet<KnowledgeChunk> KnowledgeChunks => Set<KnowledgeChunk>(); public DbSet<KnowledgeGap> KnowledgeGaps => Set<KnowledgeGap>(); public DbSet<AiAgent> AiAgents => Set<AiAgent>(); public DbSet<AiAgentVersion> AiAgentVersions => Set<AiAgentVersion>(); public DbSet<AiToolDefinition> AiToolDefinitions => Set<AiToolDefinition>(); public DbSet<AiToolExecution> AiToolExecutions => Set<AiToolExecution>(); public DbSet<PromptVersion> PromptVersions => Set<PromptVersion>(); public DbSet<QualificationFlow> QualificationFlows => Set<QualificationFlow>(); public DbSet<WorkflowNode> WorkflowNodes => Set<WorkflowNode>(); public DbSet<WorkflowEdge> WorkflowEdges => Set<WorkflowEdge>(); public DbSet<QualificationAnswer> QualificationAnswers => Set<QualificationAnswer>(); public DbSet<ScoringRule> ScoringRules => Set<ScoringRule>();
    public DbSet<IntegrationConnection> IntegrationConnections => Set<IntegrationConnection>(); public DbSet<IntegrationSyncJob> IntegrationSyncJobs => Set<IntegrationSyncJob>(); public DbSet<FieldMapping> FieldMappings => Set<FieldMapping>(); public DbSet<WebhookSubscription> WebhookSubscriptions => Set<WebhookSubscription>(); public DbSet<WebhookDelivery> WebhookDeliverys => Set<WebhookDelivery>(); public DbSet<AutomationRule> AutomationRules => Set<AutomationRule>(); public DbSet<AutomationRun> AutomationRuns => Set<AutomationRun>(); public DbSet<EvaluationDataset> EvaluationDatasets => Set<EvaluationDataset>(); public DbSet<EvaluationTestCase> EvaluationTestCases => Set<EvaluationTestCase>(); public DbSet<EvaluationRun> EvaluationRuns => Set<EvaluationRun>(); public DbSet<EvaluationResult> EvaluationResults => Set<EvaluationResult>();
    public DbSet<MetricSnapshot> MetricSnapshots => Set<MetricSnapshot>(); public DbSet<RevenueAttribution> RevenueAttributions => Set<RevenueAttribution>(); public DbSet<Plan> Plans => Set<Plan>(); public DbSet<Subscription> Subscriptions => Set<Subscription>(); public DbSet<UsageRecord> UsageRecords => Set<UsageRecord>(); public DbSet<BillingInvoice> BillingInvoices => Set<BillingInvoice>(); public DbSet<SsoConfiguration> SsoConfigurations => Set<SsoConfiguration>(); public DbSet<DataRetentionPolicy> DataRetentionPolicys => Set<DataRetentionPolicy>(); public DbSet<ConsentRecord> ConsentRecords => Set<ConsentRecord>(); public DbSet<PiiRedactionJob> PiiRedactionJobs => Set<PiiRedactionJob>(); public DbSet<Agency> Agencys => Set<Agency>(); public DbSet<AgencyClient> AgencyClients => Set<AgencyClient>(); public DbSet<BrandingProfile> BrandingProfiles => Set<BrandingProfile>(); public DbSet<CustomDomain> CustomDomains => Set<CustomDomain>(); public DbSet<IndustryPack> IndustryPacks => Set<IndustryPack>(); public DbSet<TenantIndustryPack> TenantIndustryPacks => Set<TenantIndustryPack>();
    public DbSet<ProductCategory> ProductCategories => Set<ProductCategory>(); public DbSet<CatalogProduct> CatalogProducts => Set<CatalogProduct>(); public DbSet<ProductVariant> ProductVariants => Set<ProductVariant>(); public DbSet<ProductAsset> ProductAssets => Set<ProductAsset>(); public DbSet<ProductLocalization> ProductLocalizations => Set<ProductLocalization>(); public DbSet<TargetMarket> TargetMarkets => Set<TargetMarket>(); public DbSet<ProductPromotionPlan> ProductPromotionPlans => Set<ProductPromotionPlan>(); public DbSet<PortalPublication> PortalPublications => Set<PortalPublication>(); public DbSet<PortalInquiry> PortalInquiries => Set<PortalInquiry>();
    public DbSet<Facility> Facilities => Set<Facility>(); public DbSet<FacilityCapability> FacilityCapabilities => Set<FacilityCapability>(); public DbSet<CustomerAccount> CustomerAccounts => Set<CustomerAccount>(); public DbSet<PriceList> PriceLists => Set<PriceList>(); public DbSet<PriceListItem> PriceListItems => Set<PriceListItem>(); public DbSet<SalesOrder> SalesOrders => Set<SalesOrder>(); public DbSet<SalesOrderItem> SalesOrderItems => Set<SalesOrderItem>(); public DbSet<Fulfillment> Fulfillments => Set<Fulfillment>(); public DbSet<FulfillmentItem> FulfillmentItems => Set<FulfillmentItem>(); public DbSet<StockBalance> StockBalances => Set<StockBalance>(); public DbSet<StockReservation> StockReservations => Set<StockReservation>(); public DbSet<StockMovement> StockMovements => Set<StockMovement>(); public DbSet<Shipment> Shipments => Set<Shipment>(); public DbSet<RoutePlan> RoutePlans => Set<RoutePlan>(); public DbSet<RouteStop> RouteStops => Set<RouteStop>(); public DbSet<CommercialDocument> CommercialDocuments => Set<CommercialDocument>(); public DbSet<Payment> Payments => Set<Payment>(); public DbSet<PaymentAllocation> PaymentAllocations => Set<PaymentAllocation>();
    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder); builder.ConfigureBusinessEntityKeys(); builder.ConfigurePlatformModel(); builder.ConfigureCrmModel(); builder.ConfigureAcquisitionModel(); builder.ConfigureAutonomousAcquisitionModel(); builder.ConfigureConversationSupportModel(); builder.ConfigureKnowledgeAiModel();
        builder.Entity<ProductCategory>(e => { e.ToTable("ProductCategories"); e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(256).IsRequired(); e.Property(x => x.Code).HasMaxLength(128); e.HasIndex(x => new { x.TenantId, x.Code }); });
        builder.Entity<CatalogProduct>(e => { e.ToTable("CatalogProducts"); e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(256).IsRequired(); e.Property(x => x.Code).HasMaxLength(128).IsRequired(); e.Property(x => x.Brand).HasMaxLength(128); e.HasIndex(x => new { x.TenantId, x.Code }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.ProductCategoryId }); });
        builder.Entity<ProductVariant>(e => { e.ToTable("ProductVariants"); e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(256).IsRequired(); e.Property(x => x.Sku).HasMaxLength(128); e.Property(x => x.NetWeight).HasPrecision(18,3); e.HasIndex(x => new { x.TenantId, x.CatalogProductId }); });
        builder.Entity<ProductAsset>(e => { e.ToTable("ProductAssets"); e.HasKey(x => x.Id); e.Property(x => x.AssetType).HasMaxLength(64).IsRequired(); e.Property(x => x.FileName).HasMaxLength(512).IsRequired(); e.Property(x => x.Uri).HasMaxLength(2048).IsRequired(); e.HasIndex(x => new { x.TenantId, x.CatalogProductId }); });
        builder.Entity<ProductLocalization>(e => { e.ToTable("ProductLocalizations"); e.HasKey(x => x.Id); e.Property(x => x.Language).HasMaxLength(16).IsRequired(); e.Property(x => x.Name).HasMaxLength(256).IsRequired(); e.HasIndex(x => new { x.TenantId, x.CatalogProductId, x.Language }).IsUnique(); });
        builder.Entity<TargetMarket>(e => { e.ToTable("TargetMarkets"); e.HasKey(x => x.Id); e.Property(x => x.CountryCode).HasMaxLength(8).IsRequired(); e.Property(x => x.CountryName).HasMaxLength(128).IsRequired(); e.Property(x => x.DefaultLanguage).HasMaxLength(16).IsRequired(); e.HasIndex(x => new { x.TenantId, x.CatalogProductId, x.CountryCode }).IsUnique(); });
        builder.Entity<ProductPromotionPlan>(e => { e.ToTable("ProductPromotionPlans"); e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(256).IsRequired(); e.Property(x => x.CampaignLanguage).HasMaxLength(16).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.CatalogProductId, x.TargetMarketId }); });
        builder.Entity<PortalPublication>(e => { e.ToTable("PortalPublications"); e.HasKey(x => x.Id); e.Property(x => x.Slug).HasMaxLength(256).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.CatalogProductId }).IsUnique(); e.HasIndex(x => new { x.TenantId, x.Slug }).IsUnique(); });
        builder.Entity<PortalInquiry>(e => { e.ToTable("PortalInquiries"); e.HasKey(x => x.Id); e.Property(x => x.Name).HasMaxLength(256).IsRequired(); e.Property(x => x.Email).HasMaxLength(320).IsRequired(); e.Property(x => x.Language).HasMaxLength(16).IsRequired(); e.Property(x => x.Status).HasMaxLength(32).IsRequired(); e.HasIndex(x => new { x.TenantId, x.CreatedAt }); });
        builder.Entity<TenantEntitlementProjection>(entity => { entity.ToTable("TenantEntitlements"); entity.HasKey(x => x.TenantId); entity.Property(x => x.TenantSlug).HasMaxLength(128).IsRequired(); entity.Property(x => x.TenantStatus).HasMaxLength(32).IsRequired(); entity.Property(x => x.LicensePlan).HasMaxLength(64).IsRequired(); entity.Property(x => x.LicenseStatus).HasMaxLength(32).IsRequired(); entity.Property(x => x.ModulesJson).IsRequired(); entity.Property(x => x.LimitsJson).IsRequired(); });
        builder.Entity<TenantModuleProvisioning>(entity => { entity.ToTable("TenantModuleProvisionings"); entity.HasKey(x => new { x.TenantId, x.ModuleCode }); entity.Property(x => x.ModuleCode).HasMaxLength(128); entity.Property(x => x.Status).HasMaxLength(32).IsRequired(); entity.Property(x => x.LastError).HasMaxLength(4000); entity.HasIndex(x => new { x.Status, x.NextRetryAtUtc }); });
        builder.Entity<TenantLifecycleEventRecord>(entity => { entity.ToTable("TenantLifecycleEvents"); entity.HasKey(x => x.Id); entity.Property(x => x.Type).HasMaxLength(64).IsRequired(); entity.Property(x => x.Status).HasMaxLength(64).IsRequired(); entity.Property(x => x.Message).HasMaxLength(2000).IsRequired(); entity.Property(x => x.Source).HasMaxLength(128).IsRequired(); entity.Property(x => x.DataJson).HasMaxLength(4000); entity.Property(x => x.CorrelationId).HasMaxLength(128); entity.Property(x => x.ActorId).HasMaxLength(256); entity.HasIndex(x => new { x.TenantId, x.OccurredAtUtc }); entity.HasIndex(x => x.CorrelationId); });
        builder.Entity<BillingEventRecord>(entity => { entity.ToTable("BillingEvents"); entity.HasKey(x => x.Id); entity.Property(x => x.Provider).HasMaxLength(64).IsRequired(); entity.Property(x => x.ExternalEventId).HasMaxLength(256).IsRequired(); entity.Property(x => x.Type).HasMaxLength(128).IsRequired(); entity.Property(x => x.Status).HasMaxLength(64).IsRequired(); entity.Property(x => x.DataJson).HasMaxLength(4000); entity.HasIndex(x => new { x.Provider, x.ExternalEventId }).IsUnique(); entity.HasIndex(x => new { x.TenantId, x.OccurredAtUtc }); });
        builder.Entity<TenantBillingSubscriptionRecord>(entity => { entity.ToTable("TenantBillingSubscriptions"); entity.HasKey(x => x.Id); entity.Property(x => x.Provider).HasMaxLength(64).IsRequired(); entity.Property(x => x.ExternalSubscriptionId).HasMaxLength(256).IsRequired(); entity.Property(x => x.Plan).HasMaxLength(128).IsRequired(); entity.Property(x => x.Status).HasMaxLength(64).IsRequired(); entity.HasIndex(x => new { x.Provider, x.ExternalSubscriptionId }).IsUnique(); entity.HasIndex(x => x.TenantId).IsUnique(); });
        builder.Entity<TenantBillingInvoiceRecord>(entity => { entity.ToTable("TenantBillingInvoices"); entity.HasKey(x => x.Id); entity.Property(x => x.Provider).HasMaxLength(64).IsRequired(); entity.Property(x => x.ExternalInvoiceId).HasMaxLength(256).IsRequired(); entity.Property(x => x.Status).HasMaxLength(64).IsRequired(); entity.Property(x => x.Currency).HasMaxLength(8).IsRequired(); entity.Property(x => x.AmountDue).HasPrecision(18,2); entity.Property(x => x.AmountPaid).HasPrecision(18,2); entity.HasIndex(x => new { x.Provider, x.ExternalInvoiceId }).IsUnique(); entity.HasIndex(x => new { x.TenantId, x.UpdatedAtUtc }); });
        builder.Entity<TenantBillingLifecycleRecord>(entity => { entity.ToTable("TenantBillingLifecycles"); entity.HasKey(x => x.TenantId); entity.Property(x => x.State).HasMaxLength(64).IsRequired(); entity.Property(x => x.LastPaymentState).HasMaxLength(128); entity.HasIndex(x => new { x.State, x.NextRetryAtUtc }); });
        builder.Entity<AutonomousAcquisitionAgentMemory>(entity => { entity.ToTable("AutonomousAcquisitionAgentMemories"); entity.HasKey(x => x.Id); entity.Property(x => x.Key).HasMaxLength(256).IsRequired(); entity.Property(x => x.Category).HasMaxLength(64).IsRequired(); entity.Property(x => x.Value).HasMaxLength(4000).IsRequired(); entity.HasIndex(x => new { x.TenantId, x.AgentId, x.Category, x.Key }).IsUnique(); });
    }
}
