<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Infrastructure/QualifyAI.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../Core/Domain/QualifyAI.Identity.Domain.csproj" />
    <ProjectReference Include="../Core/Application/QualifyAI.Identity.Application.csproj" />
    <ProjectReference Include="../../../src/Shared/QualifyAI.BuildingBlocks.Messaging/QualifyAI.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="../../../src/Shared/QualifyAI.BuildingBlocks.Security/QualifyAI.BuildingBlocks.Security.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
  </ItemGroup>
</Project>
