<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../LeadsAI.Integrations.Domain/LeadsAI.Integrations.Domain.csproj" />
<ProjectReference Include="../../../../Shared/LeadsAI.BuildingBlocks.Application/LeadsAI.BuildingBlocks.Application.csproj" />
<ProjectReference Include="../../../../Shared/LeadsAI.BuildingBlocks.Messaging/LeadsAI.BuildingBlocks.Messaging.csproj" />
    <PackageReference Include="MediatR" /><PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>