<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../QualifyAI.Integrations.Domain/QualifyAI.Integrations.Domain.csproj" />
    <ProjectReference Include="../QualifyAI.Integrations.Application/QualifyAI.Integrations.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/QualifyAI.BuildingBlocks.Messaging/QualifyAI.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="../../../Contracts/QualifyAI.Contracts/QualifyAI.Contracts.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
  </ItemGroup>
</Project>
