<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../QualifyAI.Knowledge.Application/QualifyAI.Knowledge.Application.csproj" />
<ProjectReference Include="../QualifyAI.Knowledge.Infrastructure/QualifyAI.Knowledge.Infrastructure.csproj" />
<ProjectReference Include="../../../QualifyAI.ServiceDefaults/QualifyAI.ServiceDefaults.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" /><PackageReference Include="Swashbuckle.AspNetCore" />
      <ProjectReference Include="../../../BuildingBlocks/QualifyAI.BuildingBlocks.Messaging/QualifyAI.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>
</Project>