using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QualifyAI.Persistence.SqlServer.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260909140000_AddRenovaCatalogPortal")]
public partial class AddRenovaCatalogPortal : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "ProductCategories", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), ParentCategoryId = table.Column<Guid>(nullable: true), Name = table.Column<string>(maxLength: 256, nullable: false), Code = table.Column<string>(maxLength: 128, nullable: true), Description = table.Column<string>(nullable: true), SortOrder = table.Column<int>(nullable: false), IsActive = table.Column<bool>(nullable: false) }, constraints: table => table.PrimaryKey("PK_ProductCategories", x => x.Id));
        migrationBuilder.CreateTable(name: "CatalogProducts", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), ProductCategoryId = table.Column<Guid>(nullable: false), Name = table.Column<string>(maxLength: 256, nullable: false), Code = table.Column<string>(maxLength: 128, nullable: false), Brand = table.Column<string>(maxLength: 128, nullable: true), ShortDescription = table.Column<string>(nullable: true), Description = table.Column<string>(nullable: true), KeyBenefits = table.Column<string>(nullable: true), Applications = table.Column<string>(nullable: true), TechnicalSpecifications = table.Column<string>(nullable: true), IsActive = table.Column<bool>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), UpdatedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_CatalogProducts", x => x.Id));
        migrationBuilder.CreateTable(name: "ProductVariants", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: false), Name = table.Column<string>(maxLength: 256, nullable: false), Sku = table.Column<string>(maxLength: 128, nullable: true), Packaging = table.Column<string>(nullable: true), NetWeight = table.Column<decimal>(type: "decimal(18,3)", nullable: true), WeightUnit = table.Column<string>(nullable: true), Color = table.Column<string>(nullable: true), Specifications = table.Column<string>(nullable: true), IsActive = table.Column<bool>(nullable: false) }, constraints: table => table.PrimaryKey("PK_ProductVariants", x => x.Id));
        migrationBuilder.CreateTable(name: "ProductAssets", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: false), AssetType = table.Column<string>(maxLength: 64, nullable: false), FileName = table.Column<string>(maxLength: 512, nullable: false), Uri = table.Column<string>(maxLength: 2048, nullable: false), Language = table.Column<string>(nullable: true), Title = table.Column<string>(nullable: true), IsPublic = table.Column<bool>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => table.PrimaryKey("PK_ProductAssets", x => x.Id));
        migrationBuilder.CreateTable(name: "ProductLocalizations", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: false), Language = table.Column<string>(maxLength: 16, nullable: false), Name = table.Column<string>(maxLength: 256, nullable: false), ShortDescription = table.Column<string>(nullable: true), Description = table.Column<string>(nullable: true), KeyBenefits = table.Column<string>(nullable: true), Applications = table.Column<string>(nullable: true) }, constraints: table => table.PrimaryKey("PK_ProductLocalizations", x => x.Id));
        migrationBuilder.CreateTable(name: "TargetMarkets", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: false), CountryCode = table.Column<string>(maxLength: 8, nullable: false), CountryName = table.Column<string>(maxLength: 128, nullable: false), DefaultLanguage = table.Column<string>(maxLength: 16, nullable: false), TargetIndustries = table.Column<string>(nullable: true), TargetCustomerTypes = table.Column<string>(nullable: true), IsActive = table.Column<bool>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => table.PrimaryKey("PK_TargetMarkets", x => x.Id));
        migrationBuilder.CreateTable(name: "ProductPromotionPlans", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: false), TargetMarketId = table.Column<Guid>(nullable: false), Name = table.Column<string>(maxLength: 256, nullable: false), CampaignLanguage = table.Column<string>(maxLength: 16, nullable: false), Status = table.Column<string>(maxLength: 32, nullable: false), TargetCustomerProfile = table.Column<string>(nullable: true), QualificationRules = table.Column<string>(nullable: true), MessagingStrategy = table.Column<string>(nullable: true), EnableAutonomousProspecting = table.Column<bool>(nullable: false), EnableAutomaticCampaignEnrollment = table.Column<bool>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), ActivatedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_ProductPromotionPlans", x => x.Id));
        migrationBuilder.CreateTable(name: "PortalPublications", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: false), Slug = table.Column<string>(maxLength: 256, nullable: false), Status = table.Column<string>(maxLength: 32, nullable: false), IsVisible = table.Column<bool>(nullable: false), Version = table.Column<int>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), PublishedAt = table.Column<DateTimeOffset>(nullable: true), UpdatedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_PortalPublications", x => x.Id));
        migrationBuilder.CreateTable(name: "PortalInquiries", columns: table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), CatalogProductId = table.Column<Guid>(nullable: true), Name = table.Column<string>(maxLength: 256, nullable: false), Company = table.Column<string>(nullable: true), Email = table.Column<string>(maxLength: 320, nullable: false), Phone = table.Column<string>(nullable: true), CountryCode = table.Column<string>(nullable: true), Language = table.Column<string>(maxLength: 16, nullable: false), Message = table.Column<string>(nullable: true), Status = table.Column<string>(maxLength: 32, nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => table.PrimaryKey("PK_PortalInquiries", x => x.Id));
        migrationBuilder.CreateIndex(name: "IX_ProductCategories_TenantId_Code", table: "ProductCategories", columns: new[] { "TenantId", "Code" }); migrationBuilder.CreateIndex(name: "IX_CatalogProducts_TenantId_Code", table: "CatalogProducts", columns: new[] { "TenantId", "Code" }, unique: true); migrationBuilder.CreateIndex(name: "IX_ProductVariants_TenantId_CatalogProductId", table: "ProductVariants", columns: new[] { "TenantId", "CatalogProductId" }); migrationBuilder.CreateIndex(name: "IX_ProductAssets_TenantId_CatalogProductId", table: "ProductAssets", columns: new[] { "TenantId", "CatalogProductId" }); migrationBuilder.CreateIndex(name: "IX_ProductLocalizations_TenantId_CatalogProductId_Language", table: "ProductLocalizations", columns: new[] { "TenantId", "CatalogProductId", "Language" }, unique: true); migrationBuilder.CreateIndex(name: "IX_TargetMarkets_TenantId_CatalogProductId_CountryCode", table: "TargetMarkets", columns: new[] { "TenantId", "CatalogProductId", "CountryCode" }, unique: true); migrationBuilder.CreateIndex(name: "IX_PortalPublications_TenantId_CatalogProductId", table: "PortalPublications", columns: new[] { "TenantId", "CatalogProductId" }, unique: true); migrationBuilder.CreateIndex(name: "IX_PortalPublications_TenantId_Slug", table: "PortalPublications", columns: new[] { "TenantId", "Slug" }, unique: true); migrationBuilder.CreateIndex(name: "IX_PortalInquiries_TenantId_CreatedAt", table: "PortalInquiries", columns: new[] { "TenantId", "CreatedAt" });
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("PortalInquiries"); migrationBuilder.DropTable("PortalPublications"); migrationBuilder.DropTable("ProductPromotionPlans"); migrationBuilder.DropTable("TargetMarkets"); migrationBuilder.DropTable("ProductLocalizations"); migrationBuilder.DropTable("ProductAssets"); migrationBuilder.DropTable("ProductVariants"); migrationBuilder.DropTable("CatalogProducts"); migrationBuilder.DropTable("ProductCategories"); }
}
