<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../QualifyAI.Integrations.Domain/QualifyAI.Integrations.Domain.csproj" />
<ProjectReference Include="../../../../Shared/QualifyAI.BuildingBlocks.Application/QualifyAI.BuildingBlocks.Application.csproj" />
<ProjectReference Include="../../../../Shared/QualifyAI.BuildingBlocks.Messaging/QualifyAI.BuildingBlocks.Messaging.csproj" />
    <PackageReference Include="MediatR" /><PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>